//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"os"
	"regexp"
	"strconv"
)

func main() {
	const inPath = "../../Resources/PMDWinS036-master/fmgen/opna.c"
	const outPath = "fm_tables_gen.go"

	raw, err := os.ReadFile(inPath)
	if err != nil {
		panic(err)
	}
	re := regexp.MustCompile(`(?s)static int16_t sinetable\[1024\] = \{(.*?)\};`)
	match := re.FindSubmatch(raw)
	if match == nil {
		panic("sinetable not found")
	}
	values := regexp.MustCompile(`-?\d+`).FindAll(match[1], -1)
	if len(values) != 1024 {
		panic(fmt.Sprintf("sinetable length mismatch: %d", len(values)))
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by go run gen_fmtables.go; DO NOT EDIT.\n")
	out.WriteString("package ym2608\n\n")
	out.WriteString("var fmSineTable = [1024]int16{\n\t")
	for i, value := range values {
		if i > 0 {
			out.WriteString(", ")
		}
		if i > 0 && i%24 == 0 {
			out.WriteString("\n\t")
		}
		n, err := strconv.Atoi(string(value))
		if err != nil {
			panic(err)
		}
		out.WriteString(strconv.Itoa(n))
	}
	out.WriteString(",\n}\n")

	if err := os.WriteFile(outPath, out.Bytes(), 0644); err != nil {
		panic(err)
	}
}
