//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"os"
	"regexp"
	"strconv"
)

func main() {
	const inPath = "../../Resources/PMDWinS036-master/fmgen/rhythmdata.h"
	const outPath = "rhythmdata_gen.go"

	raw, err := os.ReadFile(inPath)
	if err != nil {
		panic(err)
	}

	names := []string{"BD_2608", "SD_2608", "TOP_2608", "HH_2608", "TOM_2608", "RIM_2608"}
	re := regexp.MustCompile(`(?s)static const unsigned char ([A-Z_0-9]+)\[(\d+)\] = \{(.*?)\};`)
	matches := re.FindAllSubmatch(raw, -1)
	byName := map[string][]byte{}
	for _, m := range matches {
		name := string(m[1])
		wantLen, err := strconv.Atoi(string(m[2]))
		if err != nil {
			panic(err)
		}
		values := regexp.MustCompile(`0x[0-9a-fA-F]{1,2}`).FindAll(m[3], -1)
		data := make([]byte, len(values))
		for i, value := range values {
			n, err := strconv.ParseUint(string(value[2:]), 16, 8)
			if err != nil {
				panic(err)
			}
			data[i] = byte(n)
		}
		if len(data) != wantLen {
			panic(fmt.Sprintf("%s length mismatch: parsed=%d declared=%d", name, len(data), wantLen))
		}
		byName[name] = data
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by go run gen_rhythmdata.go; DO NOT EDIT.\n")
	out.WriteString("package ym2608\n\n")
	out.WriteString("var defaultRhythmSamples = [6][]int8{\n")
	for _, name := range names {
		data, ok := byName[name]
		if !ok {
			panic("missing " + name)
		}
		if len(data) < 44 {
			panic("short rhythm sample " + name)
		}
		// PMDWin skips the WAV header, halves the remaining byte count, then
		// treats the resulting range as signed 8-bit PCM.
		pcm := data[44 : 44+(len(data)-44)/2]
		out.WriteString("\t{\n\t\t")
		for i, b := range pcm {
			if i > 0 {
				out.WriteString(", ")
			}
			if i > 0 && i%24 == 0 {
				out.WriteString("\n\t\t")
			}
			out.WriteString(strconv.Itoa(int(int8(b))))
		}
		out.WriteString(",\n\t},\n")
	}
	out.WriteString("}\n")

	if err := os.WriteFile(outPath, out.Bytes(), 0644); err != nil {
		panic(err)
	}
}
