//go:build ignore

package main

/*
#cgo CFLAGS: -I${SRCDIR}/../../Resources/PMDWinS036-master/fmgen
#cgo LDFLAGS: -lm
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#define printf(...) ((int)0)
#include "../../Resources/PMDWinS036-master/fmgen/psg.c"
#include "../../Resources/PMDWinS036-master/fmgen/opna.c"
#undef printf
#include "../../Resources/PMDWinS036-master/fmgen/rhythmdata.c"

static uint8_t ncdx_gain_at(int i) {
	return ((uint8_t *)gaintab)[i & 0x7f];
}
*/
import "C"

import (
	"bytes"
	"os"
	"strconv"
)

func main() {
	var out bytes.Buffer
	out.WriteString("// Code generated by go run gen_fmgain_compat.go; DO NOT EDIT.\n")
	out.WriteString("package ym2608\n\n")
	out.WriteString("var fmGainCompatTable = [128]uint8{\n\t")
	for i := 0; i < 128; i++ {
		if i > 0 {
			out.WriteString(", ")
		}
		if i > 0 && i%24 == 0 {
			out.WriteString("\n\t")
		}
		out.WriteString(strconv.Itoa(int(C.ncdx_gain_at(C.int(i)))))
	}
	out.WriteString(",\n}\n")

	if err := os.WriteFile("fm_gain_compat_gen.go", out.Bytes(), 0644); err != nil {
		panic(err)
	}
}
